# Generated by Django 6.0 on 2026-01-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audience',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('genz', 'GenZ'), ('unizex', 'Unisex')], default='men', max_length=10),
        ),
    ]
