# Generated by Django 6.0 on 2026-02-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
